### ISSUE TITLE
Module version mismatch. Expected 46, got 48.

### ISSUE THREAD

**Issue by skeddles** [jduncanator/node-diskusage#31]
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/workspace/node_modules/diskusage/index.js:1:76)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

```

var disk = require("diskusage");

disk.check('/', function(err, info) {
    if (err) {
        console.log(err);
    } else {
        console.log(info.available);
        console.log(info.free);
        console.log(info.total);
    }
});
 
try {
    var info = disk.checkSync('/');
    console.log(info.available);
    console.log(info.free);
    console.log(info.total);
}
catch (err) {
    console.log(err);
}
```

**Comment by jduncanator** [comment]
Looks like you're trying to use a version of diskusage installed with a different version of node.js. Try installing the package again with `npm install diskusage` on the machine you're trying to use it.

**Comment by jduncanator** [comment]
Closing unless more information can be provided.
