### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by deeepaaa** [jduncanator/node-diskusage#9]
Happens whenever I try requiring this module.

`Error: Module did not self-register.

```
at Error (native)

at Object.Module._extensions..node (module.js:568:18)

at Module.load (module.js:458:32)

at tryModuleLoad (module.js:417:12)

at Function.Module._load (module.js:409:3)

at Module.require (module.js:468:17)

at require (internal/module.js:20:19)

at bindings (/home/depa/Documents/hachidori/node_modules/diskusage/node_modules/ref/node_modules/bindings/bindings.js:76:44)

at Object.<anonymous> (/home/depa/Documents/hachidori/node_modules/diskusage/node_modules/ref/lib/ref.js:5:47)

at Module._compile (module.js:541:32)
```

`

**Comment by jduncanator** [comment]
What version of NodeJS are you using? I may need to update the node-ffi dependency again.

**Comment by deeepaaa** [comment]
@jduncanator I'm using version 6.2.0

**Comment by DomVinyard** [comment]
I'm hitting this same error on node v4.4.5.

**Comment by jduncanator** [comment]
Interesting. I'll update the dependencies of ref and ffi to see if that fixes some of the issues.

**Comment by jduncanator** [comment]
@deeepaaa @DomVinyard Think this may be relevant: http://stackoverflow.com/questions/28486891/uncaught-error-module-did-not-self-register

Try rebuilding the gyp modules, and if that fails, reinstalling all the modules. If it's still not working, let me know and I'll take a further look into it.

**Comment by robogen** [comment]
On #10 before I updated my nodejs version, I was using nw-gyp to rebuild ref and ffi on my Scientific Linux machine after installing diskusage, and that got the module working. Could there be a backwards compatibility issue with ref and the updated node-gyp?

**Comment by jduncanator** [comment]
As of version 0.2.0 diskusage now uses native, platform specific bindings. This should resolve any of the previous installation issues. If you are still experiencing issues, feel free to comment on this issue and I will take a further look.
